// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7_TO_BE_REPLACED',
    appId: '1:368459758861:web:TO_BE_REPLACED',
    messagingSenderId: '368459758861',
    projectId: 'flash-4523a',
    authDomain: 'flash-4523a.firebaseapp.com',
    storageBucket: 'flash-4523a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7_TO_BE_REPLACED',
    appId: '1:368459758861:android:TO_BE_REPLACED',
    messagingSenderId: '368459758861',
    projectId: 'flash-4523a',
    authDomain: 'flash-4523a.firebaseapp.com',
    storageBucket: 'flash-4523a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTWLL9gFloPHYGvv_r4o28fJ7J8FZ4kEA',
    appId: '1:368459758861:ios:78281ed79d847fcdc9c444',
    messagingSenderId: '368459758861',
    projectId: 'flash-4523a',
    authDomain: 'flash-4523a.firebaseapp.com',
    iosBundleId: 'com.example.flashCompositionApp',
    storageBucket: 'flash-4523a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7_TO_BE_REPLACED',
    appId: '1:368459758861:macos:TO_BE_REPLACED',
    messagingSenderId: '368459758861',
    projectId: 'flash-4523a',
    authDomain: 'flash-4523a.firebaseapp.com',
    iosBundleId: 'com.example.flashCompositionApp',
    storageBucket: 'flash-4523a.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7_TO_BE_REPLACED',
    appId: '1:368459758861:windows:TO_BE_REPLACED',
    messagingSenderId: '368459758861',
    projectId: 'flash-4523a',
    authDomain: 'flash-4523a.firebaseapp.com',
    storageBucket: 'flash-4523a.appspot.com',
  );
}
